-- 1. Buat tabel untuk Petisi Warga
CREATE TABLE petitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  signatures INTEGER DEFAULT 1,
  target INTEGER NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Buat tabel untuk Penggalangan Dana
CREATE TABLE funds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  collected BIGINT DEFAULT 0,
  target BIGINT NOT NULL,
  donors INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Masukkan data awal (Dummy Data) agar tidak kosong
INSERT INTO petitions (title, status, signatures, target, date) VALUES
('Perbaikan Lampu Jalan RT 03', 'approved', 145, 150, '2026-07-01'),
('Pembangunan Saluran Air Antisipasi Banjir', 'pending', 89, 200, '2026-07-05');

INSERT INTO funds (title, collected, target, donors) VALUES
('Renovasi Poskamling RW 05', 1500000, 5000000, 34);
